def coList():
    countries = ['Syria',
        'Turkey',
        'Greece',
        'Bulgaria',
        'Romania',
        'Serbia',
        'Macedonia',
        'Albania',
        'Montenegro',
        'Bosnia',
        'Hungary',
        'Croatia',
        'Slovenia',
        'Italy',
        'Switzerland',
        'Austria',
        'Germany',
        'Czech Republic',
        'Slovakia',
        'Poland',
        'Finland',
        'Sweden',
        'Norway',
        'Denmark',
        'Netherlands',
        'Belgium',
        'France',
        'UK',
        'Spain',
        'Portugal',
        'Malta',
        'Morocco',
        'Algeria',
        'Tunisia',
        'Libya',
        'Egypt',
        'Israel',
        'Jordan',
        'Lebanon']
    return countries

def countries(): 
    countries = {'Syria': 0,
        'Turkey': 1,
        'Greece': 2,
        'Bulgaria': 3,
        'Romania': 4,
        'Serbia': 5,
        'Macedonia': 6,
        'Albania': 7,
        'Montenegro': 8,
        'Bosnia': 9,
        'Hungary': 10,
        'Croatia': 11,
        'Slovenia': 12,
        'Italy': 13,
        'Switzerland': 14,
        'Austria': 15,
        'Germany': 16,
        'Czech Republic': 17,
        'Slovakia': 18,
        'Poland': 19,
        'Finland': 20,
        'Sweden': 21,
        'Norway': 22,
        'Denmark': 23,
        'Netherlands': 24,
        'Belgium': 25,
        'France': 26,
        'UK': 27,
        'Spain': 28,
        'Portugal': 29,
        'Malta': 30,
        'Morocco': 31,
        'Algeria': 32,
        'Tunisia': 33,
        'Libya': 34,
        'Egypt': 35,
        'Israel': 36,
        'Jordan': 37,
        'Lebanon': 38}
    return countries

def contiguousBorders(countries):
    edges = [ (countries['Syria'], countries['Turkey']),
        (countries['Syria'], countries['Lebanon']),
        (countries['Turkey'], countries['Bulgaria']),
        #(countries['Turkey'], countries['Greece']), 
        (countries['Bulgaria'], countries['Greece']), 
        (countries['Bulgaria'], countries['Romania']), 
        (countries['Bulgaria'], countries['Macedonia']), 
        (countries['Romania'], countries['Serbia']), 
        (countries['Romania'], countries['Hungary']), 
        (countries['Greece'], countries['Macedonia']), 
        (countries['Greece'], countries['Albania']), 
        (countries['Albania'], countries['Macedonia']), 
        (countries['Albania'], countries['Montenegro']), 
        (countries['Montenegro'], countries['Serbia']), 
        (countries['Montenegro'], countries['Bosnia']) ,
        (countries['Bosnia'], countries['Croatia']),
        (countries['Serbia'], countries['Hungary']),
        (countries['Hungary'], countries['Slovakia']),
        (countries['Hungary'], countries['Austria']),
        (countries['Croatia'], countries['Hungary']),
        (countries['Croatia'], countries['Slovenia']),
        (countries['Slovenia'], countries['Austria']),
        (countries['Slovenia'], countries['Italy']),
        (countries['Italy'], countries['Austria']),
        (countries['Italy'], countries['Switzerland']),
        (countries['Italy'], countries['France']),
        (countries['Switzerland'], countries['Austria']),
        (countries['Switzerland'], countries['Germany']),
        (countries['Switzerland'], countries['France']),
        (countries['Germany'], countries['Austria']),
        (countries['Germany'], countries['Denmark']),
        (countries['Germany'], countries['Netherlands']),
        (countries['Germany'], countries['Belgium']),
        (countries['Germany'], countries['Switzerland']),
        (countries['Austria'], countries['Germany']),
        (countries['Austria'], countries['Switzerland']),
        (countries['Czech Republic'], countries['Poland']), ## ??
        (countries['Czech Republic'], countries['Germany']),
        (countries['Czech Republic'], countries['Austria']),
        (countries['Poland'], countries['Czech Republic']),
        (countries['Poland'], countries['Germany']),
        (countries['Denmark'], countries['Sweden']),
        (countries['Norway'], countries['Sweden']),
        (countries['Norway'], countries['Finland']),
        (countries['Sweden'], countries['Finland']),
        (countries['Sweden'], countries['Norway']),
        (countries['Finland'], countries['Sweden']),
        (countries['Finland'], countries['Norway']),
        (countries['Netherlands'], countries['Germany']),
        (countries['Netherlands'], countries['Belgium']),
        (countries['Belgium'], countries['Netherlands']),
        (countries['Belgium'], countries['Germany']),
        (countries['Belgium'], countries['France']),
        (countries['France'], countries['Belgium']),
        (countries['France'], countries['Switzerland']),
        (countries['Spain'], countries['Portugal']),
        (countries['Spain'], countries['France']),
        (countries['Morocco'], countries['Algeria']),
        (countries['Tunisia'], countries['Algeria']),
        (countries['Libya'], countries['Tunisia']),
        (countries['Libya'], countries['Algeria']),
        (countries['Egypt'], countries['Libya']),
        (countries['Israel'], countries['Egypt']),
        (countries['Israel'], countries['Jordan']),
        (countries['Jordan'], countries['Egypt']),
        (countries['Slovakia'], countries['Poland']),
        (countries['Slovakia'], countries['Czech Republic']),
        (countries['Slovakia'], countries['Austria']),
        (countries['Lebanon'], countries['Israel'])  ] ##,
        #(countries[''], countries['']),
        #(countries[''], countries['']),
        #(countries[''], countries['']),
        # ]
    return edges
    
def waterRoutes(countries):
    waterRoutes = [ (countries['Egypt'], countries['Greece']),
        (countries['Turkey'], countries['Greece']),
        (countries['Greece'], countries['Italy']),
        (countries['Libya'], countries['Italy']),
        (countries['Libya'], countries['Malta']),
        (countries['Tunisia'], countries['Malta']),
        (countries['Algeria'], countries['France']),
        (countries['Algeria'], countries['Spain']),
        (countries['Morocco'], countries['Spain']),
        (countries['Malta'], countries['Italy']),
        (countries['France'], countries['UK']),
        (countries['Poland'], countries['Sweden']),
        (countries['Poland'], countries['Finland']),
        (countries['Poland'], countries['Norway']),
        (countries['Germany'], countries['Finland']),
        (countries['Germany'], countries['Sweden']),
        (countries['Germany'], countries['Norway']),
        (countries['Denmark'], countries['Norway']),
        (countries['Denmark'], countries['Finland']),
        (countries['Finland'], countries['Denmark']),
        (countries['Norway'], countries['Denmark'])  ]  ##,
        #(countries[''], countries['']),
    return waterRoutes
    
def africaCountries():
    return [ 'Morocco',
        'Algeria',
        'Tunisia', 
        'Libya',
        'Egypt'
    ]
    
def middleEastCountries():
    return [ 'Israel',
        'Jordan',
        'Lebanon',
        'Syria'
    ]
    
    
def nordicCountries():
    return ['Denmark',
        'Norway',
        'Sweden',
        'Finland'
    ]
    
def westernEuropeCountries():
    return ['France',
        'Belgium',
        'Netherlands',
        'Germany',
        'Switzerland',
        'Austria',
        'UK'
    ]
    
def centralEuropeCountries():
    return ['Slovenia',
        'Czech Republic',
        'Poland',
        'Bulgaria',
        'Romania',
        'Hungary',
        'Slovakia'
    ]
    
def southernEuropeCountries():
    return ['Portugal',
        'Spain',
        'Italy',
        'Slovenia',
        'Croatia',
        'Bosnia',
        'Montenegro',
        'Albania',
        'Greece',
        'Serbia',
        'Turkey',
        'Malta',
        'Macedonia'
    ]
    
def countryList():
    return countries()
    
    
def distanceBetweenCountries(): 
    countries = countryList()
        
    distances = {(countries['Albania'],countries['Macedonia']):.15 ,
            (countries['Albania'],countries['Montenegro']): .15,
            (countries['Algeria'],countries['France']):.9 ,
            (countries['Algeria'],countries['Spain']):.9 ,
            (countries['Austria'],countries['Germany']):.4 ,
            (countries['Austria'],countries['Switzerland']):.4 ,
            (countries['Belgium'],countries['Germany']):.4 ,
            (countries['Belgium'],countries['Netherlands']):.15 ,
            (countries['Belgium'],countries['France']):.4 ,
            (countries['Bosnia'],countries['Croatia']):.15 ,
            (countries['Bulgaria'],countries['Greece']):.4 ,
            (countries['Bulgaria'],countries['Macedonia']):.4 ,
            (countries['Bulgaria'],countries['Romania']):.4 ,
            (countries['Czech Republic'],countries['Austria']):.15 ,
            (countries['Czech Republic'],countries['Germany']):.4 ,
            (countries['Czech Republic'],countries['Poland']):.15 ,
            (countries['Croatia'],countries['Hungary']):.4 ,
            (countries['Croatia'],countries['Slovenia']):.15 ,
            (countries['Denmark'],countries['Finland']):.9 ,
            (countries['Denmark'],countries['Norway']):.4 ,
            (countries['Denmark'],countries['Sweden']):.65 ,
            (countries['Egypt'],countries['Greece']):.9 ,
            (countries['Egypt'],countries['Libya']):.9 ,
            (countries['France'],countries['Belgium']):.4 ,
            (countries['France'],countries['Switzerland']):.4 ,
            (countries['France'],countries['UK']):.9 ,
            (countries['Finland'],countries['Denmark']):.9 ,
            (countries['Finland'],countries['Sweden']):.4 ,
            (countries['Finland'],countries['Norway']):.65 ,
            (countries['Germany'],countries['Austria']):.4 ,
            (countries['Germany'],countries['Belgium']):.4 ,
            (countries['Germany'],countries['Denmark']):.4 ,
            (countries['Germany'],countries['Finland']):.9 ,
            (countries['Germany'],countries['Netherlands']):.4 ,
            (countries['Germany'],countries['Norway']):.9 ,
            (countries['Germany'],countries['Sweden']):.9 ,
            (countries['Germany'],countries['Switzerland']):.4 ,
            (countries['Greece'],countries['Albania']):.15 ,
            (countries['Greece'],countries['Italy']):.65 ,
            (countries['Greece'],countries['Macedonia']):.15 ,
            (countries['Hungary'],countries['Austria']):.4 ,
            (countries['Hungary'],countries['Slovakia']):.15 ,
            (countries['Israel'],countries['Egypt']):.65 ,
            (countries['Israel'],countries['Jordan']):.15 ,
            (countries['Italy'],countries['Austria']):.65 ,
            (countries['Italy'],countries['France']):.65 ,
            (countries['Italy'],countries['Switzerland']):.65 ,
            (countries['Jordan'],countries['Egypt']):.65 ,
            (countries['Lebanon'],countries['Israel']):.4 ,
            (countries['Libya'],countries['Algeria']):.9 ,
            (countries['Libya'],countries['Italy']):.9 ,
            (countries['Libya'],countries['Malta']):.9 ,
            (countries['Libya'],countries['Tunisia']):.9 ,
            (countries['Macedonia'],countries['Serbia']):.15 ,
            (countries['Malta'],countries['Italy']):.4 ,
            (countries['Montenegro'],countries['Bosnia']):.15 ,
            (countries['Montenegro'],countries['Serbia']):.15 ,
            (countries['Morocco'],countries['Algeria']):.65 ,
            (countries['Morocco'],countries['Spain']):.9 ,
            (countries['Netherlands'],countries['Germany']):.4 ,
            (countries['Netherlands'],countries['Belgium']):.15 ,
            (countries['Norway'],countries['Finland']):.65 ,
            (countries['Norway'],countries['Sweden']):.4 ,
            (countries['Norway'],countries['Denmark']):.4 ,
            (countries['Poland'],countries['Czech Republic']):.15 ,
            (countries['Poland'],countries['Finland']):.9 ,
            (countries['Poland'],countries['Germany']):.65 ,
            (countries['Poland'],countries['Norway']):.9 ,
            (countries['Poland'],countries['Sweden']):.65 ,
            (countries['Romania'],countries['Hungary']):.4 ,
            (countries['Romania'],countries['Serbia']):.4 ,
            (countries['Serbia'],countries['Hungary']):.4 ,
            (countries['Slovakia'],countries['Austria']):.15 ,
            (countries['Slovakia'],countries['Czech Republic']):.4 ,
            (countries['Slovakia'],countries['Poland']):.4 ,
            (countries['Slovenia'],countries['Austria']):.15 ,
            (countries['Slovenia'],countries['Italy']):.4 ,
            (countries['Spain'],countries['France']):.65 ,
            (countries['Spain'],countries['Portugal']):.4 ,
            (countries['Sweden'],countries['Finland']):.4 ,
            (countries['Sweden'],countries['Norway']):.4 ,
            (countries['Switzerland'],countries['Austria']):.4 ,
            (countries['Switzerland'],countries['France']):.4 ,
            (countries['Switzerland'],countries['Germany']):.4 ,
            (countries['Syria'],countries['Lebanon']):.4 ,
            (countries['Syria'],countries['Turkey']):.4 ,
            (countries['Tunisia'],countries['Algeria']):.65 ,
            (countries['Tunisia'],countries['Malta']):.4 ,
            (countries['Turkey'],countries['Bulgaria']):.65 ,
            (countries['Turkey'],countries['Greece']):.9 
        }
#    print distances
    return distances






    

if __name__ == '__main__':
    #countries = countries()
    #print contiguousBorders(countries)
    #print coList()
    distances = distanceBetweenCountries()
    print distances[(1,2)]

